### ISSUE TITLE
CustomParams

### ISSUE THREAD

**Issue by 89z** [raitonoberu/ytsearch#3]
I see the current code look like this:

https://github.com/raitonoberu/ytsearch/blob/70e7bfef1d1b1310c29709982cddde4f0e2ff6b8/search.go#L49-L53

I found out the search params are Protobuf encoded:

~~~go
package main

import (
   "encoding/base64"
   "fmt"
   p "google.golang.org/protobuf/testing/protopack"
)

func encode(key p.Number, val int) string {
   m := p.Message{
      p.Tag{2, p.BytesType}, p.LengthPrefix{
         p.Tag{key, p.VarintType}, p.Varint(val),
      },
   }
   b := m.Marshal()
   return "&sp=" + base64.StdEncoding.EncodeToString(b)
}

func main() {
   s := encode(2, 2) // Channel
   fmt.Println(s == "&sp=EgIQAg==")
   s = encode(3, 1) // Under 4 minutes
   fmt.Println(s == "&sp=EgIYAQ==")
}
~~~

just wanted to mention it in case you were interested.

**Comment by raitonoberu** [comment]
This is very valuable information. I spent a lot of time trying to understand how these parameters are combined, and you did it.

**Comment by 89z** [comment]
If youre interested, I think I have the full list of decoded params here:

https://github.com/89z/mech/blob/c6583a6a/research/2021-08-24/param.go

**Comment by 89z** [comment]
Closing this in favor of my own package:

https://github.com/89z/mech/blob/v1.37.1/youtube/proto.go
