### ISSUE TITLE
Index Out Of Range Exception

### ISSUE THREAD

**Issue by thenhawke** [raitonoberu/ytsearch#4]
When searching, very rarely, the parser will throw an "index out of range exception" depending on what is being searched. Here's an example:

```
package main

import "github.com/raitonoberu/ytmusic"

func main() {
	srch := ytmusic.Search("panama")
	srch.Next()
}
```

**Comment by raitonoberu** [comment]
YouTube Music repository is here: https://github.com/raitonoberu/ytmusic

**Comment by raitonoberu** [comment]
Stacktrace:
